#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ENV_FILE:-$PROJECT_DIR/.env}"

if [ "$(id -u)" -ne 0 ]; then
  echo "Run as root: sudo bash scripts/setup_payment_nginx.sh"
  exit 1
fi

if [ ! -f "$ENV_FILE" ]; then
  echo ".env not found: $ENV_FILE"
  echo "Create it first: cp .env.example .env"
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

DOMAIN="${PAYMENT_CALLBACK_DOMAIN:-}"
if [ -z "$DOMAIN" ] && [ -n "${TETRAPAY_CALLBACK_URL:-}" ]; then
  DOMAIN="$(python3 - <<PY
from urllib.parse import urlparse
print(urlparse('${TETRAPAY_CALLBACK_URL}').hostname or '')
PY
)"
fi

if [ -z "$DOMAIN" ] && [ -n "${PLISIO_CALLBACK_URL:-}" ]; then
  DOMAIN="$(python3 - <<PY2
from urllib.parse import urlparse
print(urlparse('${PLISIO_CALLBACK_URL}').hostname or '')
PY2
)"
fi

if [ -z "$DOMAIN" ]; then
  echo "PAYMENT_CALLBACK_DOMAIN, TETRAPAY_CALLBACK_URL or PLISIO_CALLBACK_URL is required in .env"
  exit 1
fi

HOST="${PAYMENT_WEBHOOK_HOST:-127.0.0.1}"
PORT="${PAYMENT_WEBHOOK_PORT:-8081}"
SITE_NAME="${NGINX_PAYMENT_SITE_NAME:-payment-callback}"
DISABLE_CONFLICTS="${NGINX_PAYMENT_DISABLE_CONFLICTS:-1}"
ENABLE_HTTPS="${NGINX_PAYMENT_ENABLE_HTTPS:-0}"
SSL_CERT="${NGINX_PAYMENT_SSL_CERT:-}"
SSL_KEY="${NGINX_PAYMENT_SSL_KEY:-}"
SITE_AVAILABLE="/etc/nginx/sites-available/${SITE_NAME}.conf"
SITE_ENABLED="/etc/nginx/sites-enabled/${SITE_NAME}.conf"
BACKUP_DIR="/etc/nginx/payment-callback-disabled-$(date +%Y%m%d-%H%M%S)"

if ! command -v nginx >/dev/null 2>&1; then
  echo "Installing nginx..."
  apt-get update
  apt-get install -y nginx
fi

mkdir -p /etc/nginx/sites-available /etc/nginx/sites-enabled

if [ "$DISABLE_CONFLICTS" = "1" ]; then
  mkdir -p "$BACKUP_DIR"
  echo "Checking duplicate enabled nginx configs for $DOMAIN..."
  # Disable duplicate enabled site symlinks/files that contain the same server_name.
  # This prevents HTTPS/HTTP requests from being handled by an old vhost and returning 404.
  for path in /etc/nginx/sites-enabled/* /etc/nginx/conf.d/*.conf; do
    [ -e "$path" ] || continue
    [ "$path" = "$SITE_ENABLED" ] && continue
    if grep -Eq "server_name[[:space:]][^;]*\b${DOMAIN}\b" "$path" 2>/dev/null; then
      base="$(basename "$path")"
      echo "Disabling conflicting config: $path"
      mv "$path" "$BACKUP_DIR/$base.disabled"
    fi
  done
fi

cat > "$SITE_AVAILABLE" <<EOF
# Auto generated by scripts/setup_payment_nginx.sh
# Domain: ${DOMAIN}
# Upstream: http://${HOST}:${PORT}

server {
    listen 80;
    server_name ${DOMAIN};

    location = /health {
        proxy_pass http://${HOST}:${PORT}/health;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location /payments/ {
        proxy_pass http://${HOST}:${PORT}/payments/;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location / {
        default_type text/plain;
        return 200 "payment callback server\\n";
    }
}
EOF

if [ "$ENABLE_HTTPS" = "1" ]; then
  if [ -z "$SSL_CERT" ] || [ -z "$SSL_KEY" ]; then
    echo "NGINX_PAYMENT_ENABLE_HTTPS=1 but NGINX_PAYMENT_SSL_CERT or NGINX_PAYMENT_SSL_KEY is empty."
    echo "Either set certificate paths in .env, or set NGINX_PAYMENT_ENABLE_HTTPS=0 and use Cloudflare Flexible."
    exit 1
  fi
  if [ ! -f "$SSL_CERT" ] || [ ! -f "$SSL_KEY" ]; then
    echo "SSL certificate/key not found:"
    echo "NGINX_PAYMENT_SSL_CERT=$SSL_CERT"
    echo "NGINX_PAYMENT_SSL_KEY=$SSL_KEY"
    exit 1
  fi
  cat >> "$SITE_AVAILABLE" <<EOF

server {
    listen 443 ssl;
    server_name ${DOMAIN};

    ssl_certificate ${SSL_CERT};
    ssl_certificate_key ${SSL_KEY};

    location = /health {
        proxy_pass http://${HOST}:${PORT}/health;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location /payments/ {
        proxy_pass http://${HOST}:${PORT}/payments/;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location / {
        default_type text/plain;
        return 200 "payment callback server https\\n";
    }
}
EOF
fi

ln -sf "$SITE_AVAILABLE" "$SITE_ENABLED"

nginx -t
systemctl enable nginx >/dev/null 2>&1 || true
systemctl reload nginx || systemctl restart nginx

echo "Nginx payment callback config installed."
echo "Domain: $DOMAIN"
echo "Internal health: http://${HOST}:${PORT}/health"
echo "Public HTTP health: http://${DOMAIN}/health"
echo "Public HTTPS health: https://${DOMAIN}/health"
if [ "$ENABLE_HTTPS" != "1" ]; then
  echo "HTTPS 404 means Cloudflare is probably using origin HTTPS and hitting another 443 vhost."
  echo "Fix options: set Cloudflare SSL/TLS to Flexible, or set NGINX_PAYMENT_ENABLE_HTTPS=1 with cert paths."
fi

echo "Running quick local nginx test..."
curl -fsS "http://127.0.0.1/health" -H "Host: ${DOMAIN}" || true
echo
